### PR TITLE
Add stashes check

### PR DESCRIPTION
**Pull request by mathiasvr**
Detects if the repository contains stashed changes.

### CODE REVIEW

**Comment by watson** [comment]
Thank you 😃 I like the addition of knowing how many stashes there is.

Only problem I see with this PR is that you've made it part of the general "issues" check - so having something stashed will now be seen as an issue by other modules relying on this value. This might work for some peoples workflows, but I'd say it's certainly a breaking change.

I think the solution to this is to simply move the whole concept of "issues" out into another module as this is actually not directly related to the state of the git-repo.

I'll merge your PR, remove the issues code and release it as a major version.

Please comment if you have a better idea 😃

**Comment by watson** [comment]
I've now published this as v3.0.0, but with the issues part removed

**Comment by mathiasvr** [comment]
Thanks!
Could this check be added to `code-status`, or would that be inappropriate?

**Comment by watson** [comment]
@mathiasvr Good idea. I just published it as code-status@3.0.0

**Pull request merged**
